/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andri' at '3/29/17 10:34 PM' with Gradle 2.14.1
 *
 * @author andri, @date 3/29/17 10:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
